//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Biuro/Scripts/InputActions/GameControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameControls"",
    ""maps"": [
        {
            ""name"": ""Game"",
            ""id"": ""c7532128-58e6-43d1-908f-ccb9a273e016"",
            ""actions"": [
                {
                    ""name"": ""GoBack"",
                    ""type"": ""Button"",
                    ""id"": ""170a40e1-d769-4d67-8e6f-a66b86eaf604"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""PassThrough"",
                    ""id"": ""3d90b2db-b09d-4469-afaa-c6c223e798e0"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseLeftClick"",
                    ""type"": ""Button"",
                    ""id"": ""367e25cf-183a-4a80-9ae6-940faba00799"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangePlayerCamera"",
                    ""type"": ""Button"",
                    ""id"": ""9c90c2ac-5648-4130-af5b-495bf330c29d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Scroll"",
                    ""type"": ""Value"",
                    ""id"": ""04dc5bc3-6b12-40a8-806a-e0162a6e5be2"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""OpenNoteBook"",
                    ""type"": ""Button"",
                    ""id"": ""978847db-54a8-4ee5-960c-e7040788b129"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""71841adb-ff04-4a1a-a26d-faad01b9d15f"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GoBack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""13fa91e4-3fb2-46d8-bcbb-18b1c053a973"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a97c75c-4d8b-4422-9078-8c966f0a84fa"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseLeftClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a829457f-8e82-40be-ab59-b4b98819f87e"",
                    ""path"": ""<Keyboard>/f5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangePlayerCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""611ea79c-9899-46ac-bf6e-f66852792716"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Scroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""acad3036-8725-4421-b4e8-64ac3b7d5520"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenNoteBook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Game
        m_Game = asset.FindActionMap("Game", throwIfNotFound: true);
        m_Game_GoBack = m_Game.FindAction("GoBack", throwIfNotFound: true);
        m_Game_MousePosition = m_Game.FindAction("MousePosition", throwIfNotFound: true);
        m_Game_MouseLeftClick = m_Game.FindAction("MouseLeftClick", throwIfNotFound: true);
        m_Game_ChangePlayerCamera = m_Game.FindAction("ChangePlayerCamera", throwIfNotFound: true);
        m_Game_Scroll = m_Game.FindAction("Scroll", throwIfNotFound: true);
        m_Game_OpenNoteBook = m_Game.FindAction("OpenNoteBook", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Game
    private readonly InputActionMap m_Game;
    private IGameActions m_GameActionsCallbackInterface;
    private readonly InputAction m_Game_GoBack;
    private readonly InputAction m_Game_MousePosition;
    private readonly InputAction m_Game_MouseLeftClick;
    private readonly InputAction m_Game_ChangePlayerCamera;
    private readonly InputAction m_Game_Scroll;
    private readonly InputAction m_Game_OpenNoteBook;
    public struct GameActions
    {
        private @GameControls m_Wrapper;
        public GameActions(@GameControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @GoBack => m_Wrapper.m_Game_GoBack;
        public InputAction @MousePosition => m_Wrapper.m_Game_MousePosition;
        public InputAction @MouseLeftClick => m_Wrapper.m_Game_MouseLeftClick;
        public InputAction @ChangePlayerCamera => m_Wrapper.m_Game_ChangePlayerCamera;
        public InputAction @Scroll => m_Wrapper.m_Game_Scroll;
        public InputAction @OpenNoteBook => m_Wrapper.m_Game_OpenNoteBook;
        public InputActionMap Get() { return m_Wrapper.m_Game; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameActions set) { return set.Get(); }
        public void SetCallbacks(IGameActions instance)
        {
            if (m_Wrapper.m_GameActionsCallbackInterface != null)
            {
                @GoBack.started -= m_Wrapper.m_GameActionsCallbackInterface.OnGoBack;
                @GoBack.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnGoBack;
                @GoBack.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnGoBack;
                @MousePosition.started -= m_Wrapper.m_GameActionsCallbackInterface.OnMousePosition;
                @MousePosition.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnMousePosition;
                @MousePosition.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnMousePosition;
                @MouseLeftClick.started -= m_Wrapper.m_GameActionsCallbackInterface.OnMouseLeftClick;
                @MouseLeftClick.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnMouseLeftClick;
                @MouseLeftClick.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnMouseLeftClick;
                @ChangePlayerCamera.started -= m_Wrapper.m_GameActionsCallbackInterface.OnChangePlayerCamera;
                @ChangePlayerCamera.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnChangePlayerCamera;
                @ChangePlayerCamera.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnChangePlayerCamera;
                @Scroll.started -= m_Wrapper.m_GameActionsCallbackInterface.OnScroll;
                @Scroll.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnScroll;
                @Scroll.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnScroll;
                @OpenNoteBook.started -= m_Wrapper.m_GameActionsCallbackInterface.OnOpenNoteBook;
                @OpenNoteBook.performed -= m_Wrapper.m_GameActionsCallbackInterface.OnOpenNoteBook;
                @OpenNoteBook.canceled -= m_Wrapper.m_GameActionsCallbackInterface.OnOpenNoteBook;
            }
            m_Wrapper.m_GameActionsCallbackInterface = instance;
            if (instance != null)
            {
                @GoBack.started += instance.OnGoBack;
                @GoBack.performed += instance.OnGoBack;
                @GoBack.canceled += instance.OnGoBack;
                @MousePosition.started += instance.OnMousePosition;
                @MousePosition.performed += instance.OnMousePosition;
                @MousePosition.canceled += instance.OnMousePosition;
                @MouseLeftClick.started += instance.OnMouseLeftClick;
                @MouseLeftClick.performed += instance.OnMouseLeftClick;
                @MouseLeftClick.canceled += instance.OnMouseLeftClick;
                @ChangePlayerCamera.started += instance.OnChangePlayerCamera;
                @ChangePlayerCamera.performed += instance.OnChangePlayerCamera;
                @ChangePlayerCamera.canceled += instance.OnChangePlayerCamera;
                @Scroll.started += instance.OnScroll;
                @Scroll.performed += instance.OnScroll;
                @Scroll.canceled += instance.OnScroll;
                @OpenNoteBook.started += instance.OnOpenNoteBook;
                @OpenNoteBook.performed += instance.OnOpenNoteBook;
                @OpenNoteBook.canceled += instance.OnOpenNoteBook;
            }
        }
    }
    public GameActions @Game => new GameActions(this);
    public interface IGameActions
    {
        void OnGoBack(InputAction.CallbackContext context);
        void OnMousePosition(InputAction.CallbackContext context);
        void OnMouseLeftClick(InputAction.CallbackContext context);
        void OnChangePlayerCamera(InputAction.CallbackContext context);
        void OnScroll(InputAction.CallbackContext context);
        void OnOpenNoteBook(InputAction.CallbackContext context);
    }
}
